module.exports = function (self) {
	self.setVariableDefinitions({
		connection: { name: 'Connection status' },
		device_name: { name: 'Device name' },
		group_name: { name: 'Group name' },
		uuid: { name: 'Device UUID' },
		mac: { name: 'MAC address' },
		firmware: { name: 'Firmware version' },
		project: { name: 'Project/model code' },
		configured_host: { name: 'Configured/discovered host' },
		discovered_host: { name: 'Subnet scan discovered host' },
		discovery_status: { name: 'Discovery status' },
		protocol: { name: 'Active protocol' },
		mode: { name: 'Input/source mode raw' },
		source: { name: 'Input/source name' },
		selected_source: { name: 'Selected source for encoder preset' },
		status: { name: 'Playback status raw' },
		status_text: { name: 'Playback status text' },
		volume: { name: 'Volume' },
		mute: { name: 'Mute state' },
		loop_mode: { name: 'Loop mode raw' },
		loop_mode_text: { name: 'Loop mode text' },
		shuffle: { name: 'Shuffle state' },
		position_seconds: { name: 'Playback position seconds' },
		duration_seconds: { name: 'Track duration seconds' },
		position_time: { name: 'Playback position time' },
		duration_time: { name: 'Track duration time' },
		progress_percent: { name: 'Playback progress percent' },
		artist: { name: 'Artist' },
		album: { name: 'Album' },
		title: { name: 'Track title' },
		subtitle: { name: 'Subtitle' },
		track_id: { name: 'Track ID' },
		uri: { name: 'Track URI' },
		artwork_url: { name: 'Artwork URL' },
		sample_rate: { name: 'Sample rate' },
		bit_depth: { name: 'Bit depth' },
		bit_rate: { name: 'Bit rate' },
		eq_enabled: { name: 'EQ enabled' },
		eq_preset: { name: 'EQ preset' },
		preset_count: { name: 'Preset count' },
		preset_summary: { name: 'Preset summary' },
		now_playing: { name: 'Now playing summary' },
		api_last_command: { name: 'Documented API last command' },
		api_last_endpoint: { name: 'Documented API last endpoint' },
		api_last_tag: { name: 'Documented API last tag' },
		api_last_summary: { name: 'Documented API last summary' },
		api_last_response: { name: 'Documented API last response' },
		api_last_error: { name: 'Documented API last error' },
		media_library_count: { name: 'Media library file count' },
		media_library_status: { name: 'Media library scan status' },
		selected_media_file: { name: 'Selected media file for encoder preset' },
		selected_media_url: { name: 'Selected media URL for encoder preset' },
		random_media_file: { name: 'Last random media file' },
		random_media_url: { name: 'Last random media URL' },
		auto_random_next: { name: 'Auto random next status' },
		auto_random_folder_filter: { name: 'Auto random folder filter' },
		assisted_repeat_one: { name: 'Assisted repeat one status' },
	})
}
